import type { SnapshotChain } from "./registry";
import snapshot from "./pools.snapshot.json";

/**
 * Pools known at build time, keyed by chainId. Generated by
 * `npm run pools:snapshot` (scripts/snapshot-pools.mts) — commit the result
 * whenever pools are launched so fresh visitors only scan the delta.
 */
type Snapshot = { generatedAt: string; chains: Record<string, SnapshotChain> };

const SNAPSHOT = snapshot as Snapshot;

export function snapshotFor(chainId: number): SnapshotChain | null {
  return SNAPSHOT.chains[String(chainId)] ?? null;
}

export const SNAPSHOT_GENERATED_AT = SNAPSHOT.generatedAt;
